from models.equipamento import Equipamento
from models.emprestimo import Emprestimo


class RepositorioEmprestimo:
    def buscar_equipamento(self, id: int) -> Equipamento: ...

    def salvar_emprestimo(self, emprestimo: Emprestimo) -> None: ...

    def buscar_emprestimo(self, id: int) -> Emprestimo: ...

    def marcar_indisponivel(self, equip_id: int) -> None: ...

    def marcar_disponivel(self, equip_id: int) -> None: ...

    def marcar_devolvido(self, emprestimo_id: int) -> None: ...

    def listar_em_atraso(self) -> list: ...

    def proximo_id_emprestimo(self) -> int: ...
